### ISSUE TITLE
useStickyGroupSeparators=true cause lag in long list

### ISSUE THREAD

**Issue by Nyan274** [Dimibe/grouped_list#26] opened 2020-04-06 22:29 UTC
Thanks for awesome library.
What i have noticed is with lots of items. 500+, the list will lag after scrolling to 400+.

**Comment by Dimibe** [comment] 2020-06-23 10:14
With release 3.2.0 some performance improvements where added. Please check If the issue is solved for you. 
I‘ll close this issue, please refer to #38 for further problems with performance.

**Closed by Dimibe** 2020-06-23 10:14 UTC
Labels: bug
