### ISSUE TITLE
Implicit animations for items when data source changes

### ISSUE THREAD

**Issue by aytunch** [Dimibe/grouped_list#190] opened 2023-08-31 21:37 UTC
Just like Flutter's `AnimatedList` widget, if this package supports animating, it would be the Swiss knife of lists :)
Do you think it is a valid feature request?
https://api.flutter.dev/flutter/widgets/AnimatedList-class.html

**Comment by Dimibe** [comment] 2023-11-15 13:23
Duplicate of #35

**Closed by Dimibe** 2023-11-15 13:23 UTC
